server:
  port: 8761

spring:
  application:
    name: eureka-server
  freemarker:
    suffix: .ftl
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","classpath:/templates/"]


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
  dashboard:
    path: /eureka